wandb:
    use: True
    project: ""
    entity : ""
    tags   : 

training:
    only_l2: True
    batch_size: 
    epochs: 
    n_iters: 
    log_freq: 
    lpips_weight:
    gan_weight_max:
    t0:
    k:

optim:
    weight_decay: 
    optimizer: "AdamW"
    lr: 
    lr_discriminator: 
    beta1: 
    amsgrad: True
    eps: 
    grad_clip: 

data:
    number_deg:
    crop_size:
    scale: 
    channels: 3
    debug: -1 # -1 No debugging, N number of debugging samples
    num_workers: 8
    ssl_datasets: [
                    "",
                    ]

generator:
    pick : 0
    models:
        -   arch: "esrgan"
            model: "generator"
            in_ch: 3
            out_ch: 3
            num_feat: 64
            scale: 4
            num_intermediate_ch: 32
            num_blocks: 23
            ckpt: #"/model_zoo/RealESRGAN_x4plus.pth"

discriminator:
    pick : 0
    models:
        -   arch: "spectralunet"
            model: "discriminator"
            in_ch: 3
            num_feat: 64
            ckpt: #"/model_zoo/RealESRGAN_x4plus_netD.pth"