wandb:
    use: True
    project: "ESRGAN"
    entity : "cidautai"
    tags   : ["sr"]

training:
    only_l2: False
    batch_size: 
    epochs: 
    log_freq: 
    lpips_weight: 1.0
    gan_weight_max: 0.1
    annealing: True
    start_epoch: 
    end_epoch: 
    sharp: False
    ema_flag: False

optim:
    weight_decay: 0.001
    optimizer: "AdamW"
    lr: 
    T_max: 
    eta_min: 
    lr_discriminator: 
    amsgrad: True
    eps: 0.00000001
    grad_clip: 1.0

data:
    number_deg: 
    crop_size:
    scale: 4
    channels: 3
    debug: -1 # -1 No debugging, N number of debugging samples
    num_workers: 
    ssl_datasets: []
generator:
    pick : 0
    models:
        -   arch: "esrgan"
            model: "generator"
            in_ch: 3
            out_ch: 3
            num_feat: 64
            scale: 4
            num_intermediate_ch: 32
            num_blocks: 23
            ckpt: 

discriminator:
    pick : 0
    models:
        -   arch: "spectralunet"
            model: "discriminator"
            in_ch: 3
            num_feat: 64
            ckpt: 