test:
    - DIV2K_LSDIR:
        hr: "/.../DIV2K_LSDIR/GT/validation"
        lr: "/.../DIV2K_LSDIR/bicubic/validation"
        n: 200
        scale: 4

    - RealSR:
        lr: "/.../RealSR_validation"
        n: 20